Adding new Browser flow to keycloak script (#46)
* Adding BrowserFlow with script

* Values for new projman

* tweaks

* Generate projman secret in template

Co-authored-by: Nuwan Goonasekera <2070605+nuwang@users.noreply.github.com>

diff --git a/cloudman/values.yaml b/cloudman/values.yaml
--- a/cloudman/values.yaml
+++ b/cloudman/values.yaml
@@ -33,18 +33,18 @@ helmsman_config:
       create_namespace: false
   install_templates:
     projman:
-      repo: alex
+      repo: cloudve
       chart: nextcloud
       display_name: Data Browser
       summary: Upload your data and connect external storage through Nextcloud.
       icon_url: "https://upload.wikimedia.org/wikipedia/commons/6/60/Nextcloud_Logo.svg"
       screenshot_url: assets/images/screenshot_nextcloud.png
       context:
-        oidc_client_secret: '{{ .Values.oidc_clients.nextcloud.client_secret }}'
-        oidc_client_id: '{{ .Values.oidc_clients.nextcloud.client_id }}'
         domain: '{{ .Values.global.domain }}'
         starting_dir: '/gvl'
+        keycloak_password: 'changeme'
       template: |
+        {% set oidc_client_secret = random_alphanumeric(8) + "-" + random_alphanumeric(4) + "-" + random_alphanumeric(4) + "-" + random_alphanumeric(4) + "-" + random_alphanumeric(12) %}
         postgresql:
           fullnameOverride: "{{context.project.namespace}}-nextcloud-postgresql"
           postgresqlUsername: "nextcloud"
@@ -75,6 +75,11 @@ helmsman_config:
             nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
             nginx.ingress.kubernetes.io/rewrite-target: "/$2"
 
+
+        persistence:
+          enabled: true
+          storageClass: "ebs"
+
         nextcloud:
           configs:
             path.config.php: |
@@ -91,8 +96,8 @@ helmsman_config:
                 'allow_user_to_change_display_name' => false,
                 'lost_password_link' => 'disabled',
                 'oidc_login_default_quota' => 0,
-                'oidc_login_client_id' => '{{context.oidc_client_id}}',
-                'oidc_login_client_secret' => '{{context.oidc_client_secret}}',
+                'oidc_login_client_id' => 'projman-{{context.project.namespace}}',
+                'oidc_login_client_secret' => '{{oidc_client_secret}}',
                 'oidc_login_provider_url' => 'https://{{context.domain}}/auth/realms/master',
                 'oidc_login_logout_url' => 'https://{{context.domain}}/auth/realms/master/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2F{{context.domain}}%2F{{context.project.access_path}}%2Fnextcloud%2F',
                 'oidc_login_scope' => 'openid profile',
@@ -212,6 +217,40 @@ helmsman_config:
           secrets:
             postgresql-password: "{{ random_alphanumeric(20) }}"
             db-username: "nextcloud"
+            oidc-client-id: "projman-{{context.project.namespace}}"
+            oidc-client-secret: "{{ oidc_client_secret }}"
+
+          jobs:
+            keycloak:
+              containers:
+              - name: "{{context.project.namespace}}-keycloak-projman-job"
+                image: "gempesaw/curl-jq"
+                command: ["/bin/sh", "/kc-init/update_keycloak.sh"]
+                volumeMounts:
+                  - name: kc-init
+                    mountPath: /kc-init
+                    readOnly: true
+                env:
+                  - name: CLIENT_ID
+                    value: "{{context.project.oidc_client_id}}"
+                  - name: KEYCLOAK_HTTP_PASSWORD
+                    value: "{{context.keycloak_password}}"
+                  - name: REDIRECT_URIS
+                    value: "https://{{context.domain}}/{{context.project.namespace}}/*"
+                  - name: CLIENT_SECRET
+                    valueFrom:
+                      secretKeyRef:
+                        name: "{{context.project.namespace}}-projman-secrets"
+                        key: oidc-client-secret
+                  - name: KC_URL
+                    value: "https://{{context.domain}}/auth"
+              volumes:
+                - name: kc-init
+                  configMap:
+                    name: {{context.project.namespace}}-projman-configs
+                    items:
+                      - key: "update_keycloak.sh"
+                        path: "update_keycloak.sh"
 
           configs:
             jupyter_notebook_config.py: |
@@ -221,6 +260,105 @@ helmsman_config:
               rsession-which-r=/usr/local/bin/R
               auth-none=1
               www-frame-origin={{context.domain}}
+
+            update_keycloak.sh: |
+              #!/bin/sh
+
+              # abort if any command fails
+              set -e
+              username="admin"
+
+              # get auth token
+              token=$(curl -k -s -d "client_id=admin-cli" -d "username=$username" -d "password=$KEYCLOAK_HTTP_PASSWORD" -d "grant_type=password" \
+                     "$KC_URL/realms/master/protocol/openid-connect/token" | jq -r '.access_token')
+
+              # Get ID for new browser flow
+              flowid=$(curl -X GET -k -s -H "Content-Type: application/json" -H "Authorization: bearer $token" "$KC_URL/admin/realms/master/authentication/flows" | jq -r '.[] | select(.alias=="BrowserFlowWithRoleRestrictions") | .id')
+
+              project_client=$(curl -k -s -H "Content-Type: application/json" -H "Authorization: bearer $token" "$KC_URL/admin/realms/master/clients" | \
+              jq --arg CLIENT_ID "$CLIENT_ID" -r '.[] | select(.clientId==$CLIENT_ID)')
+
+              if [ -z "$project_client" ]
+              then
+                    project_client=$(cat <<EOF
+              {
+                  "clientId": "$CLIENT_ID",
+                  "enabled": true,
+                  "clientAuthenticatorType": "client-secret",
+                  "authenticationFlowBindingOverrides":
+                  {
+                    "browser": "$flowid"
+                  },
+                  "redirectUris": ["$REDIRECT_URIS"],
+                  "publicClient": false,
+                  "secret": "$CLIENT_SECRET",
+                  "protocol": "openid-connect",
+                  "fullScopeAllowed": true,
+                  "protocolMappers": [
+                      {
+                          "name": "$CLIENT_ID-audience",
+                          "protocol": "openid-connect",
+                          "protocolMapper": "oidc-audience-mapper",
+                          "consentRequired": false,
+                          "config": {
+                              "included.client.audience": "$CLIENT_ID",
+                              "id.token.claim": "false",
+                              "access.token.claim": "true"
+                          }
+                      }
+                  ]
+              }
+              EOF
+                    )
+
+                    # add new client
+                    curl -k -X POST -H "Content-Type: application/json" -H "Authorization: bearer $token" "$KC_URL/admin/realms/master/clients" -d "$project_client"
+                    clientuuid=$(curl -k -s -H "Content-Type: application/json" -H "Authorization: bearer $token" "$KC_URL/admin/realms/master/clients" | jq --arg CLIENT_ID "$CLIENT_ID" -r '.[] | select(.clientId==$CLIENT_ID) | .id')
+                    roledata=$(cat <<EOF
+              {
+                  "name": "$CLIENT_ID"
+              }
+              EOF
+                    )
+                    curl -k -X POST -H "Content-Type: application/json" -H "Authorization: bearer $token" "$KC_URL/admin/realms/master/clients/$clientuuid/roles" -d "$roledata"
+                    roleid=$(curl -k -X GET -H "Content-Type: application/json" -H "Authorization: bearer $token" "$KC_URL/admin/realms/master/clients/$clientuuid/roles" | jq --arg CLIENT_ID "$CLIENT_ID" -r '.[] | select(.name==$CLIENT_ID) | .id')
+
+
+                    userdata=$(cat <<EOF
+              {
+                  "enabled":true,
+                  "attributes":{},
+                  "username":"$CLIENT_ID",
+                  "emailVerified":"",
+                  "email":"$CLIENT_ID@gvl.org",
+                  "firstName":"$CLIENT_ID",
+                  "lastName":"$CLIENT_ID"
+              }
+              EOF
+                    )
+
+                    # Create user for this project
+                    curl -k -X POST -H "Content-Type: application/json" -H "Authorization: bearer $token" "$KC_URL/admin/realms/master/users" -d "$userdata"
+
+                    useruuid=$(curl -k -s -H "Content-Type: application/json" -H "Authorization: bearer $token" "$KC_URL/admin/realms/master/users" | jq --arg CLIENT_ID "$CLIENT_ID" -r '.[] | select(.username==$CLIENT_ID) | .id')
+
+                    curl -k -X PUT -H "Content-Type: application/json" -H "Authorization: bearer $token" "$KC_URL/admin/realms/master/users/$useruuid/reset-password" -d "{\"type\":\"password\",\"value\":\"changeme\",\"temporary\":true}"
+                  
+                    rolemapping=$(cat <<EOF
+              [{
+                "id": "$roleid",
+                "name": "$CLIENT_ID",
+                "composite": false,
+                "clientRole": true,
+                "containerId": "$clientuuid"
+              }]
+              EOF
+                    )
+
+                    curl -k -X POST -H "Content-Type: application/json" -H "Authorization: bearer $token" "$KC_URL/admin/realms/master/users/$useruuid/role-mappings/clients/$clientuuid" -d "$rolemapping"
+              else
+                    echo "The $CLIENT_ID client already exists."
+              fi
 
             server.css: |
               #header .logo,
@@ -791,8 +929,6 @@ helmsman_config:
       icon_url: https://galaxyproject.org/images/galaxy-logos/galaxy_project_logo_square.png
       screenshot_url: assets/images/screenshot_galaxy.png
       context:
-        oidc_client_secret: '{{ .Values.oidc_clients.galaxy.client_secret }}'
-        oidc_client_id: '{{ .Values.oidc_clients.galaxy.client_id }}'
         domain: '{{ .Values.global.domain }}'
         influxdb_url: '{{ include "cloudman.influxdb_url_cluster" . }}'
         influxdb_database: '{{ include "cloudman.influxdb_database" . }}'
@@ -813,8 +949,8 @@ helmsman_config:
             <OIDC>
                 <provider name="custos">
                     <url>https://{{context.domain}}/auth</url>
-                    <client_id>{{context.oidc_client_id}}</client_id>
-                    <client_secret>{{context.oidc_client_secret}}</client_secret>
+                    <client_id>{{context.project.oidc_client_id}}</client_id>
+                    <client_secret>{{context.project.oidc_client_secret}}</client_secret>
                     <redirect_uri>https://{{context.domain}}{{context.project.access_path}}/galaxy/authnz/custos/callback</redirect_uri>
                     <enable_idp_logout>true</enable_idp_logout>
                     <realm>master</realm>
@@ -897,8 +1033,6 @@ helmsman_config:
       icon_url: https://jupyter.org/assets/hublogo.svg
       screenshot_url: assets/images/screenshot_jupyter.png
       context:
-        oidc_client_id: '{{ .Values.oidc_clients.jupyterhub.client_id }}'
-        oidc_client_secret: '{{ .Values.oidc_clients.jupyterhub.client_secret }}'
         domain: '{{ .Values.global.domain }}'
       template: |
         ingress:
@@ -917,8 +1051,8 @@ helmsman_config:
             className: oauthenticator.generic.GenericOAuthenticator
             config:
               login_service: "keycloak"
-              client_id: "{{context.oidc_client_id}}"
-              client_secret: "{{context.oidc_client_secret}}"
+              client_id: "{{context.project.oidc_client_id}}"
+              client_secret: "{{context.project.oidc_client_secret}}"
               token_url: "https://{{context.domain}}/auth/realms/master/protocol/openid-connect/token"
               userdata_url: "https://{{context.domain}}/auth/realms/master/protocol/openid-connect/userinfo"
               userdata_method: GET
@@ -981,14 +1115,12 @@ helmsman_config:
       icon_url: https://www.r-project.org/Rlogo.png
       screenshot_url: assets/images/screenshot_rstudio.png
       context:
-        oidc_client_id: '{{ .Values.oidc_clients.gatekeeper.client_id }}'
-        oidc_client_secret: '{{ .Values.oidc_clients.gatekeeper.client_secret }}'
         starting_dir: "/gvl"
         domain: '{{ .Values.global.domain }}'
       template: |
         oidc:
-          client_id: "{{context.oidc_client_id}}"
-          client_secret: {{context.oidc_client_secret}}
+          client_id: "{{context.project.oidc_client_id}}"
+          client_secret: {{context.project.oidc_client_secret}}
           discovery_url: https://{{context.domain}}/auth/realms/master
         ingress:
           access_path: "{{context.project.access_path}}/rstudio/"
@@ -1045,14 +1177,12 @@ helmsman_config:
       icon_url: https://upload.wikimedia.org/wikipedia/commons/8/82/Gnu-bash-logo.svg
       screenshot_url: assets/images/screenshot_terminal.png
       context:
-        oidc_client_id: '{{ .Values.oidc_clients.gatekeeper.client_id }}'
-        oidc_client_secret: '{{ .Values.oidc_clients.gatekeeper.client_secret }}'
         domain: '{{ .Values.global.domain }}'
         starting_dir: "/gvl"
       template: |
         oidc:
-          client_id: "{{context.oidc_client_id}}"
-          client_secret: {{context.oidc_client_secret}}
+          client_id: "{{context.project.oidc_client_id}}"
+          client_secret: {{context.project.oidc_client_secret}}
           discovery_url: https://{{context.domain}}/auth/realms/master
         ingress:
           access_path: {{context.project.access_path}}/terminalman/
@@ -1096,29 +1226,32 @@ rancher_project_id:
 global:
     domain: 192.168.99.100
 
-oidc_clients:
-  galaxy:
-    client_id: 'galaxy-auth'
-    # The client secret is required if the client is not public
-    public_client: false
-    #client_secret: 'cf84xfps-npm5-hvmb-ntui4grybqrh'
-    redirect_uris:
-      - '{{ include "cloudman.root_url" . }}/*'
-  gatekeeper:
-    client_id: 'gatekeeper'
-    #client_secret:
-    redirect_uris:
-      - '{{ include "cloudman.root_url" . }}/*'
-  jupyterhub:
-    client_id: 'jupyterhub'
-    #client_secret:
-    redirect_uris:
-      - '{{ include "cloudman.root_url" . }}/*'
-  nextcloud:
-    client_id: 'nextcloud'
-    #client_secret:
-    redirect_uris:
-      - '{{ include "cloudman.root_url" . }}/*'
+# This feature can be used to force the creation of OIDC clients
+# with the cloudman deployment. However, projman-helm will now handles
+# the client creation for the standard project isolation
+oidc_clients: {}
+  # galaxy:
+  #   client_id: 'galaxy-auth'
+  #   # The client secret is required if the client is not public
+  #   public_client: false
+  #   #client_secret: 'cf84xfps-npm5-hvmb-ntui4grybqrh'
+  #   redirect_uris:
+  #     - '{{ include "cloudman.root_url" . }}/*'
+  # terminalman:
+  #   client_id: 'terminalman'
+  #   #client_secret:
+  #   redirect_uris:
+  #     - '{{ include "cloudman.root_url" . }}/*'
+  # jupyterhub:
+  #   client_id: 'jupyterhub'
+  #   #client_secret:
+  #   redirect_uris:
+  #     - '{{ include "cloudman.root_url" . }}/*'
+  # nextcloud:
+  #   client_id: 'nextcloud'
+  #   #client_secret:
+  #   redirect_uris:
+  #     - '{{ include "cloudman.root_url" . }}/*'
 
 cloudlaunch:
   nameOverride: cloudman
@@ -1225,10 +1358,11 @@ keycloak:
   userRegistration:
     enabled: false
   keycloak:
-    username: admin
+    extraArgs: "-Dkeycloak.profile.feature.scripts=enabled"
+    username: "admin"
     # password: changeMe
     existingSecret: "{{ .Release.Name }}-keycloak-http"
-    existingSecretKey: password
+    existingSecretKey: "password"
     ingress:
       enabled: true
       # Add a null host to default to IP
@@ -1237,14 +1371,14 @@ keycloak:
       path: /auth
     persistence:
       deployPostgres: false
-      dbVendor: postgres
-      dbName: keycloak
+      dbVendor: "postgres"
+      dbName: "keycloak"
       dbPort: 5432
-      dbUser: keycloak
+      dbUser: "keycloak"
       # Will randomly generate if not specified
       # dbPassword: changeMe
       existingSecret: "{{ .Release.Name }}-postgres-keycloak-password"
-      existingSecretKey: postgres-keycloak-password
+      existingSecretKey: "postgres-keycloak-password"
     # Specifying address directly through extraEnv since `dbHost` is not run through tpl
     extraEnv: |
       - name: DB_ADDR
